DancingGoatMvc/Models/Personalization/ConditionTypes/IsInPersona/IsInPersonaListItemViewModel.cs
namespace DancingGoat.Models.Personalization
{
    public class IsInPersonaListItemViewModel
    {
        public string DisplayName
        {
            get;
            set;
        }


        public string CodeName
        {
            get;
            set;
        }


        public string ImagePath
        {
            get;
            set;
        }


        public bool Selected
        {
            get;
            set;
        }
    }
}

DancingGoatMvc/Models/Personalization/ConditionTypes/IsInPersona/IsInPersonaViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DancingGoat.Models.Personalization
{
    public class IsInPersonaViewModel
    {
        [Required]
        [Display(Name = "Persona Code Name")]
        public string PersonaCodeName { get; set; }


        public List<IsInPersonaListItemViewModel> AllPersonas { get; set; }
    }
}

DancingGoatMvc/Controllers/Personalization/ConditionTypes/IsInPersonaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using CMS.Personas;

using Kentico.PageBuilder.Web.Mvc.Personalization;

using DancingGoat.Models.Personalization;
using DancingGoat.Personalization;
using DancingGoat.Repositories;


namespace DancingGoat.Controllers.Personalization
{
    public class IsInPersonaController : ConditionTypeController<IsInPersonaConditionType>
    {
        private readonly IPersonaRepository mPersonaRepository;
        private readonly IPersonaPictureUrlCreator mPictureCreator;


        public IsInPersonaController(IPersonaRepository personaRepository, IPersonaPictureUrlCreator pictureCreator)
        {
            mPersonaRepository = personaRepository;
            mPictureCreator = pictureCreator;
        }


        [HttpPost]
        public ActionResult Index()
        {
            var conditionTypeParameters = GetParameters();
   
            var viewModel = new IsInPersonaViewModel
            {
                PersonaCodeName = conditionTypeParameters.PersonaName,
                AllPersonas = GetAllPersonas(conditionTypeParameters.PersonaName)
            };
            return PartialView("Personalization/ConditionTypes/_IsInPersonaConfiguration", viewModel);
        }


        [HttpPost]
        public ActionResult Validate(IsInPersonaViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.AllPersonas = GetAllPersonas();
                return PartialView("Personalization/ConditionTypes/_IsInPersonaConfiguration", viewModel);
            }

            var parameters = new IsInPersonaConditionType
            {
                PersonaName = viewModel.PersonaCodeName
            };

            return Json(parameters);
        }


        private List<IsInPersonaListItemViewModel> GetAllPersonas(string selectedPersonaName = "")
        {
            var allPersonas =  mPersonaRepository.GetAll().Select(persona => new IsInPersonaListItemViewModel
            {
                CodeName = persona.PersonaName,
                DisplayName = persona.PersonaDisplayName,
                ImagePath = mPictureCreator.CreatePersonaPictureUrl(persona, 50),
                Selected = persona.PersonaName == selectedPersonaName
            }).ToList();

            if (allPersonas.Count > 0 && !allPersonas.Exists(x => x.Selected))
            {
                allPersonas.First().Selected = true;
            }

            return allPersonas;
        }
    }
}

DancingGoatMvc/Views/Shared/Personalization/ConditionTypes/_IsInPersonaConfiguration.cshtml
@model DancingGoat.Models.Personalization.IsInPersonaViewModel

<link rel="stylesheet" type="text/css" href="~/Content/Personalization/ConditionTypes/IsInPersona.css">
@using (Html.BeginForm("Validate", "IsInPersona"))
{
    if (Model.AllPersonas.Count == 0)
    {
        <span class="persona-selector-dialog no-personas">@Html.GetUIString("DancingGoatMvc.ConditionType.IsInPersona.NoPersonas")</span>
    }
    else
    {
        <ul class="persona-selector-dialog">
            @for (var index = 0; index < Model.AllPersonas.Count; index++)
            {
                var persona = Model.AllPersonas[index];
                <li>
                    <label for="@Html.IdFor(x => x.AllPersonas[index])" class="line-wrapper">
                        <span class="ktc-radio">
                            <input id="@Html.IdFor(x => x.AllPersonas[index])"
                                   type="radio"
                                   name="@Html.NameFor(x => x.PersonaCodeName)"
                                   @(persona.Selected ? "checked" : String.Empty)
                                   value="@persona.CodeName">
                            <label for="@Html.IdFor(x => x.AllPersonas[index])"></label>
                        </span>
                        <span class="persona-details">
                            @Html.Image(persona.ImagePath, persona.DisplayName) @persona.DisplayName
                        </span>
                    </label>
                </li>
            }
        </ul>
    }
}